//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPJ.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivo
    {
        public int IdDispositivo { get; set; }
        public string Dispositivo1 { get; set; }
        public string di_Descripcion { get; set; }
    }
}
