//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPJ.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcclient
    {
        public string tipo { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string contacto { get; set; }
        public string direccion { get; set; }
        public string telefonos { get; set; }
        public string fax { get; set; }
        public string clase { get; set; }
        public string categoria { get; set; }
        public string zona { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string tip_aplic { get; set; }
        public string tipvta { get; set; }
        public string nomciu { get; set; }
        public string vendedor { get; set; }
        public string ruc { get; set; }
        public string cedula { get; set; }
        public string email { get; set; }
        public decimal cupo { get; set; }
        public decimal plazo { get; set; }
        public decimal porc_desc { get; set; }
        public decimal porc_segu { get; set; }
        public decimal tip_prec { get; set; }
        public string comentario { get; set; }
        public string usr_agr { get; set; }
        public string usr_cor { get; set; }
        public System.DateTime fec_agr { get; set; }
        public System.DateTime fec_cor { get; set; }
        public string pais { get; set; }
        public string cuenta { get; set; }
        public string serie { get; set; }
        public string esnatural { get; set; }
        public decimal hasnfac { get; set; }
        public decimal desnfac { get; set; }
        public decimal obligcont { get; set; }
        public string autoriza { get; set; }
        public System.DateTime validez { get; set; }
        public string ret_fue { get; set; }
        public string ret_iva { get; set; }
        public decimal pagche { get; set; }
        public decimal pagtra { get; set; }
        public string tipcta { get; set; }
        public string ctacte { get; set; }
        public string banco { get; set; }
        public bool incluye_ice { get; set; }
        public System.DateTime convenio_hasta { get; set; }
        public bool consignacion { get; set; }
        public string cod_usr { get; set; }
        public string cod_local { get; set; }
        public string celular { get; set; }
        public bool pasaporte { get; set; }
        public string cuenta_anticipo { get; set; }
        public bool bloqueado { get; set; }
        public string contacto_correo { get; set; }
    }
}
