//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPJ.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorProducto
    {
        public string Tipo { get; set; }
        public string Codigo { get; set; }
        public int Secuencia { get; set; }
        public int IdProducto { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
