//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPJ.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbultnum
    {
        public string tipo { get; set; }
        public string nombre { get; set; }
        public decimal numero { get; set; }
        public string agrega { get; set; }
        public string corrige { get; set; }
        public string elimina { get; set; }
        public string imprime { get; set; }
        public string imprime1 { get; set; }
        public bool permite_aprob { get; set; }
        public bool doc_previo { get; set; }
        public bool autoimpresor { get; set; }
        public string serie { get; set; }
        public decimal enviado { get; set; }
        public string formato1 { get; set; }
        public string formato2 { get; set; }
        public string formato3 { get; set; }
        public string usr_agr { get; set; }
        public string usr_cor { get; set; }
        public string ruta_xml { get; set; }
    }
}
