//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPJ.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcexipro
    {
        public string producto { get; set; }
        public string bodega_int { get; set; }
        public string bodega { get; set; }
        public decimal stock { get; set; }
        public decimal stock_2 { get; set; }
        public decimal orden { get; set; }
        public string usr_agr { get; set; }
        public string usr_cor { get; set; }
    }
}
