//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPJ.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcmovinv
    {
        public string tipo { get; set; }
        public decimal numero { get; set; }
        public decimal numreg { get; set; }
        public System.DateTime fecha { get; set; }
        public string producto { get; set; }
        public string nombre { get; set; }
        public string bodega { get; set; }
        public decimal fra { get; set; }
        public decimal peso { get; set; }
        public decimal und { get; set; }
        public decimal cantidad { get; set; }
        public decimal stock { get; set; }
        public string tip_ped { get; set; }
        public decimal pedido { get; set; }
        public decimal tipreg { get; set; }
        public decimal descuento { get; set; }
        public decimal precio_vta { get; set; }
        public decimal precio_lst { get; set; }
        public decimal subtotal { get; set; }
        public decimal costo_und { get; set; }
        public decimal costo { get; set; }
        public decimal promedio { get; set; }
        public decimal tip_prec { get; set; }
        public string tip_produc { get; set; }
        public decimal porc_desc { get; set; }
        public string sucursal { get; set; }
        public string cliente { get; set; }
        public string vendedor { get; set; }
        public bool servicio { get; set; }
        public string ubicacion { get; set; }
        public string motivo { get; set; }
        public bool eliminado { get; set; }
        public string usuario { get; set; }
        public System.DateTime digitado { get; set; }
        public string concepto { get; set; }
        public string comentario { get; set; }
        public string bodega_int { get; set; }
        public string lote { get; set; }
        public string usr_agr { get; set; }
        public string usr_cor { get; set; }
    }
}
