//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPJ.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcproduc
    {
        public string codigo { get; set; }
        public bool imprimir { get; set; }
        public bool bloquea { get; set; }
        public bool importado { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
        public string tipoitm { get; set; }
        public string linea { get; set; }
        public string proveedor { get; set; }
        public string grupo { get; set; }
        public string subgrupo { get; set; }
        public decimal cuantos { get; set; }
        public string unidad { get; set; }
        public decimal peso { get; set; }
        public string med_peso { get; set; }
        public string ubicacion { get; set; }
        public decimal descuento { get; set; }
        public bool coniva { get; set; }
        public bool bloqueado { get; set; }
        public bool servicio { get; set; }
        public decimal precio { get; set; }
        public decimal precio_2 { get; set; }
        public decimal precio_3 { get; set; }
        public decimal precio_4 { get; set; }
        public decimal precio_5 { get; set; }
        public decimal costo_fob { get; set; }
        public decimal costo_loc { get; set; }
        public decimal costo { get; set; }
        public decimal ult_costo { get; set; }
        public decimal minimo { get; set; }
        public decimal medio { get; set; }
        public decimal maximo { get; set; }
        public System.DateTime ult_vta { get; set; }
        public System.DateTime ult_com { get; set; }
        public decimal can_vta { get; set; }
        public decimal can_com { get; set; }
        public string prv1 { get; set; }
        public decimal pvp1 { get; set; }
        public string mar1 { get; set; }
        public string fec1 { get; set; }
        public string prv2 { get; set; }
        public decimal pvp2 { get; set; }
        public string mar2 { get; set; }
        public string fec2 { get; set; }
        public string prv3 { get; set; }
        public decimal pvp3 { get; set; }
        public string mar3 { get; set; }
        public string fec3 { get; set; }
        public string prv4 { get; set; }
        public decimal pvp4 { get; set; }
        public string mar4 { get; set; }
        public string fec4 { get; set; }
        public string prv5 { get; set; }
        public decimal pvp5 { get; set; }
        public string mar5 { get; set; }
        public string fec5 { get; set; }
        public string prv6 { get; set; }
        public decimal pvp6 { get; set; }
        public string mar6 { get; set; }
        public string fec6 { get; set; }
        public string desc_ampl { get; set; }
        public string comentario { get; set; }
        public decimal pcener { get; set; }
        public decimal pcfebr { get; set; }
        public decimal pcmarz { get; set; }
        public decimal pcabri { get; set; }
        public decimal pcmayo { get; set; }
        public decimal pcjuni { get; set; }
        public decimal pcjuli { get; set; }
        public decimal pcagos { get; set; }
        public decimal pcsept { get; set; }
        public decimal pcoctu { get; set; }
        public decimal pcnovi { get; set; }
        public decimal pcdici { get; set; }
        public decimal ppener { get; set; }
        public decimal ppfebr { get; set; }
        public decimal ppmarz { get; set; }
        public decimal ppabri { get; set; }
        public decimal ppmayo { get; set; }
        public decimal ppjuni { get; set; }
        public decimal ppjuli { get; set; }
        public decimal ppagos { get; set; }
        public decimal ppsept { get; set; }
        public decimal ppoctu { get; set; }
        public decimal ppnovi { get; set; }
        public decimal ppdici { get; set; }
        public string pdv_tipoitm { get; set; }
        public bool pdv_pizza { get; set; }
        public bool pdv_yogurt { get; set; }
        public bool ice { get; set; }
        public bool irbp { get; set; }
        public string usr_agr { get; set; }
        public string usr_cor { get; set; }
        public System.DateTime fec_agr { get; set; }
        public System.DateTime fec_cor { get; set; }
        public decimal und_uat { get; set; }
        public decimal val_uat1 { get; set; }
        public decimal val_uat2 { get; set; }
        public decimal val_uat3 { get; set; }
        public decimal val_uat4 { get; set; }
        public decimal val_uat5 { get; set; }
        public decimal val_uat6 { get; set; }
        public decimal prco_max { get; set; }
        public string ruta_foto { get; set; }
        public decimal porc_tole_op { get; set; }
        public string cuenta_ventas_no_grava { get; set; }
        public string cuenta_ventas_si_grava { get; set; }
        public string cuenta_ventas_desc_no_grava { get; set; }
        public string cuenta_ventas_desc_si_grava { get; set; }
        public bool gracostocap { get; set; }
    }
}
