//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPJ.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesNexpirion : DbContext
    {
        public EntitiesNexpirion()
            : base("name=EntitiesNexpirion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fcclient> fcclient { get; set; }
        public virtual DbSet<FX_ProveedorMigrado> FX_ProveedorMigrado { get; set; }
        public virtual DbSet<VWFX_ProveedorMigrado> VWFX_ProveedorMigrado { get; set; }
        public virtual DbSet<dbultnum> dbultnum { get; set; }
        public virtual DbSet<fcmovinv> fcmovinv { get; set; }
        public virtual DbSet<indocume> indocume { get; set; }
        public virtual DbSet<fcproduc> fcproduc { get; set; }
    }
}
