//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBPJ.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Compra = new HashSet<Compra>();
            this.ProductoDetalle = new HashSet<ProductoDetalle>();
            this.ProveedorProducto = new HashSet<ProveedorProducto>();
        }
    
        public int IdProducto { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public double CalificacionA { get; set; }
        public double CalificacionB { get; set; }
        public double CalificacionC { get; set; }
        public double CalificacionD { get; set; }
        public double PrecioA { get; set; }
        public double PrecioB { get; set; }
        public double PrecioC { get; set; }
        public double PrecioD { get; set; }
        public bool Estado { get; set; }
        public string EscogerPrecioPor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoDetalle> ProductoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorProducto> ProveedorProducto { get; set; }
    }
}
